name: Animdo CI/CD

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:

env:
  BUILD_APK: true
  BUILD_AAB: false
  SIGNING_ENABLED: false
  DEPLOY_ENABLED: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test

      # 🔹 BUILD APK
      - name: Build APK
        if: env.BUILD_APK == 'true'
        run: flutter build apk --release

      # 🔹 BUILD AAB (Play Store)
      - name: Build AAB
        if: env.BUILD_AAB == 'true'
        run: flutter build appbundle

      # 🔹 Upload APK Artifact
      - name: Upload APK
        if: env.BUILD_APK == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      # 🔹 Upload AAB Artifact
      - name: Upload AAB
        if: env.BUILD_AAB == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: app-aab
          path: build/app/outputs/bundle/release/app-release.aab